name: Node.js CI

on: [push]

jobs:
  build:
  
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        PORT: ${{secrets.PORT}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        JWT_EXPIRES: ${{secrets.JWT_EXPIRES}}
        SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
    - run: pm2 restart pm2.json
